// Pesan sisi server dalam 3 bahasa. Bahasa aktif dibaca langsung dari process.env.LANGUAGE
// (diubah dari menu Pengaturan di web, disimpan di .env), jadi pesan error/popup dari server
// ikut berganti bahasa tanpa restart.
const DICT = {
    id: {
        'auth.notLoggedIn': 'Belum login',
        'auth.tooMany': 'Terlalu banyak percobaan. Coba lagi beberapa menit.',
        'auth.wrong': 'username atau password salah',
        'auth.loginOk': 'Login Berhasil',
        'otp.noTelegram': 'Isi TELEGRAM_BOT_TOKEN dan TELEGRAM_CHAT_ID di file .env dulu.',
        'otp.wait': 'Tunggu 1 menit sebelum meminta kode lagi.',
        'otp.tgMsg': '🔐 Kode verifikasi reset password: {code}\nBerlaku 10 menit.',
        'otp.sendFail': 'Gagal mengirim pesan ke Telegram.',
        'otp.sent': 'Kode verifikasi telah dikirim ke Telegram!',
        'otp.expired': 'Kode kedaluwarsa. Minta kode baru.',
        'otp.wrong': 'Kode verifikasi salah!',
        'otp.ok': 'Verifikasi Berhasil!',
        'reset.invalid': 'Sesi reset tidak valid. Ulangi verifikasi.',
        'reset.tooShort': 'Password minimal 8 karakter!',
        'reset.mismatch': 'Konfirmasi password tidak cocok!',
        'reset.ok': 'Password berhasil diperbarui!',
        'set.saved': 'Bahasa disimpan',
        'set.badLang': 'Bahasa tidak dikenal',
        'term.disabled': 'Terminal dimatikan. Hidupkan dulu di Pengaturan > Terminal.',
        'term.noJob': 'Perintah tidak ditemukan (mungkin sudah dibersihkan dari memori server)',
        'term.on': 'Terminal dihidupkan',
        'term.off': 'Terminal dimatikan',
        'term.empty': 'Perintah kosong',
        'term.tooLong': 'Perintah terlalu panjang',
        'term.busy': 'Terlalu banyak perintah yang sedang berjalan. Tunggu atau hentikan salah satu.',
        'term.startFail': 'Gagal menjalankan perintah: {e}',
        'term.finished': 'Perintah sudah selesai',
        'term.timeout': '[waktu habis setelah {s} detik, perintah dihentikan]',

        'st.timeout': 'waktu habis (cek izin root di Magisk)',
        'st.noSu': 'Perintah su tidak ditemukan. Pastikan HP sudah di-root atau isi SU_BIN di .env',
        'st.noDisk': 'Flash disk tidak terdeteksi. Colok flash disk dan pastikan Android mengenalinya.',
        'st.noZip': 'Perintah zip tidak ditemukan. Jalankan di Termux: pkg install zip',
        'st.notFound': 'File/Folder tidak ditemukan',
        'st.exists': 'Folder atau file dengan nama tersebut sudah ada',
        'st.denied': 'Akses root ditolak. Izinkan Termux di aplikasi root (Magisk/KernelSU)',
        'st.fail': 'Operasi gagal',
        'st.notWritable': 'Folder upload tidak bisa ditulis (flash disk read-only?)',
        'st.ready': 'Siap',
        'st.listFail': 'Gagal membaca folder',
        'st.mkdirFail': 'Gagal membuat folder',
        'st.renameFail': 'Gagal mengubah nama',
        'st.rootNoDelete': 'Folder utama tidak bisa dihapus',
        'st.removeFail': 'Gagal menghapus file/folder',
        'st.pasteEmpty': 'Tidak ada item untuk dipaste',
        'st.pasteFail': 'Gagal melakukan pemindahan/penyalinan file',
        'st.importFail': 'Gagal menyalin',
        'st.rootNoCompress': 'Folder utama tidak bisa dikompres',
        'st.compressFail': 'Gagal mengompres (zip terpasang? pkg install zip)',
        'st.dlFail': 'Gagal mengunduh (untuk folder: pkg install zip)',
        'st.badFileName': 'Nama file tidak valid',
        'st.badFolderName': 'Nama folder tidak valid',
        'st.badName': 'Nama tidak valid',
        'st.noFile': 'Tidak ada file diunggah',
        'st.uploadFail': 'Upload gagal',
        'st.saveFail': 'Gagal menyimpan',
        'st.writeFail': 'Gagal menulis ke flash disk (penuh? FAT32 maksimal 4 GB per file)',
        'st.saveFileFail': 'Gagal menyimpan file',
        'st.uploadCancel': 'Upload dibatalkan',
        'rd.notFound': 'Flash disk tidak terdeteksi.',
        'rd.notRoot': ' Server tidak berjalan sebagai root (jalankan dengan su atau pakai STORAGE_MODE=root).',
        'rd.suDenied': ' su tidak memberi akses root (uid {uid}). Izinkan Termux di aplikasi root.',
        'rd.noMr': ' Root tidak dapat melihat volume penyimpanan. Pastikan akses root dan izin penyimpanan aktif.',
        'rd.vols': ' Beberapa volume terdeteksi: {vols}. Lepas volume lain dan sisakan satu flash disk.',
        'rd.empty': ' Tidak ada volume penyimpanan. Pastikan flash disk tercolok dan dikenali Android',
        'rd.storageIs': ' (isi /storage: {stg})',

        'bat.normal': 'Normal',
        'bat.high': 'Tegangan berlebih',
        'bat.crit': 'Kritis',
        'bat.low': 'Rendah',
        'bat.full': 'Penuh',
        'esp.badChannel': 'Channel relay tidak valid',
        'esp.noResp': 'ESP32 tidak merespons: {e}',
        'esp.offline': 'ESP32 offline',
        'esp.calNoData': 'Data tegangan belum tersedia atau nilai tidak valid',
        'esp.calBigDiff': 'Selisih terlalu besar (>2x). Cek wiring dan nilai resistor.',
        'esp.zeroing': 'Mengukur noise arus ±10 detik. Pastikan semua beban terlepas.',
        'esp.calSmall': 'Arus terlalu kecil (min 0.2 A) atau nilai tidak valid',
        'esp.calBigDiff2': 'Selisih terlalu besar (>2x). Cek sensor dan wiring.',
        'esp.calUnknown': 'Tipe kalibrasi tidak dikenal',
        'esp.calSaved': 'Kalibrasi disimpan',
        'esp.alert.crit': 'Sel baterai KRITIS {v} V. Matikan beban!',
        'esp.alert.low': 'Baterai rendah, sel terendah {v} V',
        'esp.alert.high': 'Tegangan sel berlebih {v} V',
        'esp.alert.delta': 'Sel tidak seimbang, selisih {v} V',
        'esp.alert.amp': 'Arus AC tinggi {a} A',
        'esp.alert.clip': 'Sinyal ACS712 melewati batas ADC ESP32. Kurangi beban atau pakai pembagi tegangan.',
        'esp.tgBack': '✅ ESP32 kembali online',
        'esp.tgOff': '📴 ESP32 tidak merespons ({e})',
        'esp.tgRecover': '✅ Pulih: ',

        'door.offline': 'Modul pintu offline (ESP8266 tidak terdeteksi)',
        'door.noResp': 'ESP8266 tidak merespons: {e}',
        'door.badSec': 'Waktu relay harus 0 sampai 10 detik',
        'door.secSet': 'Waktu relay: {s} detik',
        'door.lockOnMsg': 'Lock door aktif',
        'door.lockOffMsg': 'Lock door dimatikan',
        'door.cardNotFound': 'Kartu tidak ditemukan',
        'door.nameEmpty': 'Nama kartu tidak boleh kosong',
        'door.nameUsed': 'Nama kartu sudah dipakai',
        'door.cardName': 'Kartu {n}',
        'dlog.open': 'Pintu dibuka oleh {name}',
        'dlog.lockedTap': '{name} menempel kartu, tapi lock door sedang mati',
        'dlog.unknown': 'Kartu belum terdaftar: {uid}',
        'dlog.dup': 'Kartu {name} sudah terdaftar',
        'dlog.added': 'Kartu baru ditambahkan: {name} ({uid})',
        'dlog.enrollTimeout': 'Waktu tambah kartu habis',
        'dlog.backOnline': 'Modul pintu kembali online',
        'dlog.offline': 'Modul pintu offline (tidak merespons)',
        'dlog.remoteOpen': 'Pintu dibuka dari server (tanpa kartu)',
        'dlog.remoteClose': 'Pintu dikunci lagi dari server',
        'dlog.lockOn': 'Lock door diaktifkan (kartu bisa membuka pintu)',
        'dlog.lockOff': 'Lock door dimatikan (kartu tidak membuka pintu)',
        'dlog.relaySet': 'Waktu relay terbuka diatur {s} detik',
        'dlog.relaySetPulse': 'Waktu relay terbuka diatur {s} detik (pulsa singkat)',
        'dlog.enrollStart': 'Mode tambah kartu dimulai ({sec} detik)',
        'dlog.renamed': 'Nama kartu {old} diubah menjadi {name}',
        'dlog.deleted': 'Kartu dihapus: {name}',
        'dnote.dupToast': 'Kartu sudah terdaftar: {name}',
        'dnote.addedToast': 'Kartu baru ditambahkan: {name}',
        'dnote.timeoutToast': 'Waktu tambah kartu habis',
        'door.tgOpen': '🔓 Pintu dibuka oleh {name}',
        'door.tgUnknown': '🚨 Kartu belum terdaftar mencoba membuka pintu: {uid}',
        'door.tgOn': '✅ Modul pintu kembali online',
        'door.tgOff': '📴 Modul pintu tidak merespons ({e})'
    },
    en: {
        'auth.notLoggedIn': 'Not logged in',
        'auth.tooMany': 'Too many attempts. Try again in a few minutes.',
        'auth.wrong': 'Incorrect username or password',
        'auth.loginOk': 'Login successful',
        'otp.noTelegram': 'Fill in TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID in the .env file first.',
        'otp.wait': 'Wait 1 minute before requesting a new code.',
        'otp.tgMsg': '🔐 Password reset verification code: {code}\nValid for 10 minutes.',
        'otp.sendFail': 'Failed to send message to Telegram.',
        'otp.sent': 'Verification code has been sent to Telegram!',
        'otp.expired': 'Code expired. Request a new one.',
        'otp.wrong': 'Wrong verification code!',
        'otp.ok': 'Verification successful!',
        'reset.invalid': 'Reset session is invalid. Please verify again.',
        'reset.tooShort': 'Password must be at least 8 characters!',
        'reset.mismatch': 'Password confirmation does not match!',
        'reset.ok': 'Password updated successfully!',
        'set.saved': 'Language saved',
        'set.badLang': 'Unknown language',
        'term.disabled': 'Terminal is turned off. Turn it on first in Settings > Terminal.',
        'term.noJob': 'Command not found (it may have been cleared from server memory)',
        'term.on': 'Terminal turned on',
        'term.off': 'Terminal turned off',
        'term.empty': 'Empty command',
        'term.tooLong': 'Command is too long',
        'term.busy': 'Too many commands are running. Wait or stop one of them.',
        'term.startFail': 'Failed to run the command: {e}',
        'term.finished': 'The command has already finished',
        'term.timeout': '[timed out after {s} seconds, command stopped]',

        'st.timeout': 'timed out (check root permission in Magisk)',
        'st.noSu': 'su command not found. Make sure the phone is rooted or set SU_BIN in .env',
        'st.noDisk': 'Flash drive not detected. Plug it in and make sure Android recognizes it.',
        'st.noZip': 'zip command not found. Run in Termux: pkg install zip',
        'st.notFound': 'File/Folder not found',
        'st.exists': 'A file or folder with that name already exists',
        'st.denied': 'Root access denied. Allow Termux in your root app (Magisk/KernelSU)',
        'st.fail': 'Operation failed',
        'st.notWritable': 'Upload folder is not writable (flash drive read-only?)',
        'st.ready': 'Ready',
        'st.listFail': 'Failed to read folder',
        'st.mkdirFail': 'Failed to create folder',
        'st.renameFail': 'Failed to rename',
        'st.rootNoDelete': 'The root folder cannot be deleted',
        'st.removeFail': 'Failed to delete file/folder',
        'st.pasteEmpty': 'No items to paste',
        'st.pasteFail': 'Failed to move/copy files',
        'st.importFail': 'Failed to copy',
        'st.rootNoCompress': 'The root folder cannot be compressed',
        'st.compressFail': 'Failed to compress (zip installed? pkg install zip)',
        'st.dlFail': 'Download failed (for folders: pkg install zip)',
        'st.badFileName': 'Invalid file name',
        'st.badFolderName': 'Invalid folder name',
        'st.badName': 'Invalid name',
        'st.noFile': 'No file uploaded',
        'st.uploadFail': 'Upload failed',
        'st.saveFail': 'Failed to save',
        'st.writeFail': 'Failed to write to flash drive (full? FAT32 max 4 GB per file)',
        'st.saveFileFail': 'Failed to save file',
        'st.uploadCancel': 'Upload cancelled',
        'rd.notFound': 'Flash drive not detected.',
        'rd.notRoot': ' Server is not running as root (run with su or use STORAGE_MODE=root).',
        'rd.suDenied': ' su did not grant root access (uid {uid}). Allow Termux in your root app.',
        'rd.noMr': ' Root cannot see the storage volume. Check root access and storage permissions.',
        'rd.vols': ' Multiple volumes detected: {vols}. Unplug the others and leave one flash drive connected.',
        'rd.empty': ' No storage volume detected. Make sure the flash drive is plugged in and recognized by Android',
        'rd.storageIs': ' (/storage contents: {stg})',

        'bat.normal': 'Normal',
        'bat.high': 'Overvoltage',
        'bat.crit': 'Critical',
        'bat.low': 'Low',
        'bat.full': 'Full',
        'esp.badChannel': 'Invalid relay channel',
        'esp.noResp': 'ESP32 is not responding: {e}',
        'esp.offline': 'ESP32 offline',
        'esp.calNoData': 'Voltage data not available yet or value is invalid',
        'esp.calBigDiff': 'Difference too large (>2x). Check wiring and resistor values.',
        'esp.zeroing': 'Measuring current noise for ±10 seconds. Make sure all loads are disconnected.',
        'esp.calSmall': 'Current too small (min 0.2 A) or value is invalid',
        'esp.calBigDiff2': 'Difference too large (>2x). Check the sensor and wiring.',
        'esp.calUnknown': 'Unknown calibration type',
        'esp.calSaved': 'Calibration saved',
        'esp.alert.crit': 'Battery cell CRITICAL {v} V. Turn off the load!',
        'esp.alert.low': 'Battery low, lowest cell {v} V',
        'esp.alert.high': 'Cell overvoltage {v} V',
        'esp.alert.delta': 'Cells unbalanced, difference {v} V',
        'esp.alert.amp': 'High AC current {a} A',
        'esp.alert.clip': 'ACS712 signal exceeds ESP32 ADC range. Reduce load or use a voltage divider.',
        'esp.tgBack': '✅ ESP32 is back online',
        'esp.tgOff': '📴 ESP32 is not responding ({e})',
        'esp.tgRecover': '✅ Recovered: ',

        'door.offline': 'Door module offline (ESP8266 not detected)',
        'door.noResp': 'ESP8266 is not responding: {e}',
        'door.badSec': 'Relay time must be 0 to 10 seconds',
        'door.secSet': 'Relay time: {s} seconds',
        'door.lockOnMsg': 'Door lock enabled',
        'door.lockOffMsg': 'Door lock disabled',
        'door.cardNotFound': 'Card not found',
        'door.nameEmpty': 'Card name cannot be empty',
        'door.nameUsed': 'Card name is already taken',
        'door.cardName': 'Card {n}',
        'dlog.open': 'Door opened by {name}',
        'dlog.lockedTap': '{name} tapped a card, but the door lock is off',
        'dlog.unknown': 'Unregistered card: {uid}',
        'dlog.dup': 'Card {name} is already registered',
        'dlog.added': 'New card added: {name} ({uid})',
        'dlog.enrollTimeout': 'Add-card time expired',
        'dlog.backOnline': 'Door module is back online',
        'dlog.offline': 'Door module offline (not responding)',
        'dlog.remoteOpen': 'Door opened from server (no card)',
        'dlog.remoteClose': 'Door locked again from server',
        'dlog.lockOn': 'Door lock enabled (cards can open the door)',
        'dlog.lockOff': 'Door lock disabled (cards cannot open the door)',
        'dlog.relaySet': 'Relay open time set to {s} seconds',
        'dlog.relaySetPulse': 'Relay open time set to {s} seconds (short pulse)',
        'dlog.enrollStart': 'Add-card mode started ({sec} seconds)',
        'dlog.renamed': 'Card name {old} changed to {name}',
        'dlog.deleted': 'Card deleted: {name}',
        'dnote.dupToast': 'Card already registered: {name}',
        'dnote.addedToast': 'New card added: {name}',
        'dnote.timeoutToast': 'Add-card time expired',
        'door.tgOpen': '🔓 Door opened by {name}',
        'door.tgUnknown': '🚨 Unregistered card tried to open the door: {uid}',
        'door.tgOn': '✅ Door module is back online',
        'door.tgOff': '📴 Door module is not responding ({e})'
    },
    zh: {
        'auth.notLoggedIn': '未登录',
        'auth.tooMany': '尝试次数过多，请几分钟后再试。',
        'auth.wrong': '用户名或密码错误',
        'auth.loginOk': '登录成功',
        'otp.noTelegram': '请先在 .env 文件中填写 TELEGRAM_BOT_TOKEN 和 TELEGRAM_CHAT_ID。',
        'otp.wait': '请等待 1 分钟后再请求新验证码。',
        'otp.tgMsg': '🔐 重置密码验证码：{code}\n10 分钟内有效。',
        'otp.sendFail': '发送 Telegram 消息失败。',
        'otp.sent': '验证码已发送到 Telegram！',
        'otp.expired': '验证码已过期，请重新获取。',
        'otp.wrong': '验证码错误！',
        'otp.ok': '验证成功！',
        'reset.invalid': '重置会话无效，请重新验证。',
        'reset.tooShort': '密码至少 8 个字符！',
        'reset.mismatch': '两次输入的密码不一致！',
        'reset.ok': '密码更新成功！',
        'set.saved': '语言已保存',
        'set.badLang': '未知语言',
        'term.disabled': '终端已关闭。请先在“设置 > 终端”中开启。',
        'term.noJob': '找不到该命令（可能已从服务器内存中清除）',
        'term.on': '终端已开启',
        'term.off': '终端已关闭',
        'term.empty': '命令为空',
        'term.tooLong': '命令太长',
        'term.busy': '正在运行的命令过多，请等待或停止其中一个。',
        'term.startFail': '无法运行命令：{e}',
        'term.finished': '命令已结束',
        'term.timeout': '[已超时 {s} 秒，命令已停止]',

        'st.timeout': '超时（请检查 Magisk 中的 root 权限）',
        'st.noSu': '未找到 su 命令。请确认手机已 root，或在 .env 中设置 SU_BIN',
        'st.noDisk': '未检测到 U 盘。请插入 U 盘并确认 Android 已识别。',
        'st.noZip': '未找到 zip 命令。请在 Termux 中运行：pkg install zip',
        'st.notFound': '文件/文件夹不存在',
        'st.exists': '已存在同名文件或文件夹',
        'st.denied': 'root 访问被拒绝。请在 root 应用（Magisk/KernelSU）中允许 Termux',
        'st.fail': '操作失败',
        'st.notWritable': '上传文件夹无法写入（U 盘为只读？）',
        'st.ready': '就绪',
        'st.listFail': '读取文件夹失败',
        'st.mkdirFail': '创建文件夹失败',
        'st.renameFail': '重命名失败',
        'st.rootNoDelete': '根文件夹无法删除',
        'st.removeFail': '删除文件/文件夹失败',
        'st.pasteEmpty': '没有可粘贴的项目',
        'st.pasteFail': '移动/复制文件失败',
        'st.importFail': '复制失败',
        'st.rootNoCompress': '根文件夹无法压缩',
        'st.compressFail': '压缩失败（是否已安装 zip？pkg install zip）',
        'st.dlFail': '下载失败（文件夹需要：pkg install zip）',
        'st.badFileName': '文件名无效',
        'st.badFolderName': '文件夹名无效',
        'st.badName': '名称无效',
        'st.noFile': '没有上传文件',
        'st.uploadFail': '上传失败',
        'st.saveFail': '保存失败',
        'st.writeFail': '写入 U 盘失败（已满？FAT32 单文件最大 4 GB）',
        'st.saveFileFail': '保存文件失败',
        'st.uploadCancel': '上传已取消',
        'rd.notFound': '未检测到 U 盘。',
        'rd.notRoot': ' 服务器未以 root 运行（请用 su 运行或设置 STORAGE_MODE=root）。',
        'rd.suDenied': ' su 未授予 root 权限（uid {uid}）。请在 root 应用中允许 Termux。',
        'rd.noMr': 'root 无法查看存储卷。请检查 root 权限和存储访问权限。',
        'rd.vols': '检测到多个卷：{vols}。请拔下其他卷，只保留一个 U 盘。',
        'rd.empty': '未检测到存储卷。请确认 U 盘已插入并被 Android 识别',
        'rd.storageIs': '（/storage 内容：{stg}）',

        'bat.normal': '正常',
        'bat.high': '电压过高',
        'bat.crit': '严重',
        'bat.low': '偏低',
        'bat.full': '已满',
        'esp.badChannel': '继电器通道无效',
        'esp.noResp': 'ESP32 无响应：{e}',
        'esp.offline': 'ESP32 离线',
        'esp.calNoData': '电压数据暂不可用或数值无效',
        'esp.calBigDiff': '偏差过大（>2 倍）。请检查接线和电阻值。',
        'esp.zeroing': '正在测量电流噪声约 10 秒，请确保所有负载已断开。',
        'esp.calSmall': '电流过小（最小 0.2 A）或数值无效',
        'esp.calBigDiff2': '偏差过大（>2 倍）。请检查传感器和接线。',
        'esp.calUnknown': '未知的校准类型',
        'esp.calSaved': '校准已保存',
        'esp.alert.crit': '电池电芯严重过低 {v} V，请关闭负载！',
        'esp.alert.low': '电池电量低，最低电芯 {v} V',
        'esp.alert.high': '电芯电压过高 {v} V',
        'esp.alert.delta': '电芯不平衡，压差 {v} V',
        'esp.alert.amp': '交流电流过大 {a} A',
        'esp.alert.clip': 'ACS712 信号超出 ESP32 ADC 范围，请减小负载或使用分压器。',
        'esp.tgBack': '✅ ESP32 已恢复在线',
        'esp.tgOff': '📴 ESP32 无响应（{e}）',
        'esp.tgRecover': '✅ 已恢复：',

        'door.offline': '门禁模块离线（未检测到 ESP8266）',
        'door.noResp': 'ESP8266 无响应：{e}',
        'door.badSec': '继电器时间必须为 0 到 10 秒',
        'door.secSet': '继电器时间：{s} 秒',
        'door.lockOnMsg': '门锁已启用',
        'door.lockOffMsg': '门锁已关闭',
        'door.cardNotFound': '未找到卡片',
        'door.nameEmpty': '卡片名称不能为空',
        'door.nameUsed': '卡片名称已被使用',
        'door.cardName': '卡片 {n}',
        'dlog.open': '门已由 {name} 打开',
        'dlog.lockedTap': '{name} 刷卡了，但门锁处于关闭状态',
        'dlog.unknown': '未注册的卡片：{uid}',
        'dlog.dup': '卡片 {name} 已注册',
        'dlog.added': '新卡片已添加：{name}（{uid}）',
        'dlog.enrollTimeout': '添加卡片时间已超时',
        'dlog.backOnline': '门禁模块已恢复在线',
        'dlog.offline': '门禁模块离线（无响应）',
        'dlog.remoteOpen': '门已从服务器打开（无卡）',
        'dlog.remoteClose': '门已从服务器重新上锁',
        'dlog.lockOn': '门锁已启用（卡片可以开门）',
        'dlog.lockOff': '门锁已关闭（卡片无法开门）',
        'dlog.relaySet': '继电器开门时间设为 {s} 秒',
        'dlog.relaySetPulse': '继电器开门时间设为 {s} 秒（短脉冲）',
        'dlog.enrollStart': '添加卡片模式已开始（{sec} 秒）',
        'dlog.renamed': '卡片名称 {old} 已改为 {name}',
        'dlog.deleted': '卡片已删除：{name}',
        'dnote.dupToast': '卡片已注册：{name}',
        'dnote.addedToast': '新卡片已添加：{name}',
        'dnote.timeoutToast': '添加卡片时间已超时',
        'door.tgOpen': '🔓 门已由 {name} 打开',
        'door.tgUnknown': '🚨 有未注册卡片尝试开门：{uid}',
        'door.tgOn': '✅ 门禁模块已恢复在线',
        'door.tgOff': '📴 门禁模块无响应（{e}）'
    }
};

// t('auth.wrong') / t('st.noDisk') -> teks sesuai bahasa aktif
function t(key, vars) {
    const lang = process.env.LANGUAGE || 'id';
    let s = (DICT[lang] && DICT[lang][key] !== undefined ? DICT[lang][key] : DICT.id[key]);
    if (s === undefined) s = key;
    if (vars) s = s.replace(/\{(\w+)\}/g, (m, k) => vars[k] != null ? vars[k] : m);
    return s;
}

t.DICT = DICT;
module.exports = t;
